#!/usr/bin/env bash
# update-checksums.sh
# Maintainer-side script. Re-computes SHA256 over the four published blueprint
# artifacts and rewrites CHECKSUMS.sha256 in canonical sha256sum format.
#
# Run this before every commit that modifies any of the listed files:
#   xantham-system-v31.md
#   xantham-templates-v31.md
#   LICENSE
#   README.md
#
# Users verify against the manifest with scripts/verify-blueprint.sh.
#
# Optional install hook to automate this on every commit:
#   ln -sf ../../scripts/update-checksums.sh .git/hooks/pre-commit
# (the symlink ensures the hook runs the live script, not a snapshot of it)

set -euo pipefail

cd "$(git rev-parse --show-toplevel 2>/dev/null || dirname "$(cd "$(dirname "$0")/.." && pwd)")"

FILES=(
  "xantham-system-v31.md"
  "xantham-templates-v31.md"
  "LICENSE"
  "README.md"
)

if command -v sha256sum >/dev/null 2>&1; then
  SHA_CMD="sha256sum"
elif command -v shasum >/dev/null 2>&1; then
  SHA_CMD="shasum -a 256"
else
  echo "ERROR: install sha256sum or shasum first." >&2
  exit 1
fi

MISSING=0
for f in "${FILES[@]}"; do
  if [ ! -f "$f" ]; then
    echo "ERROR: $f not found at $(pwd)" >&2
    MISSING=1
  fi
done
[ "$MISSING" -eq 0 ] || exit 1

OUT="CHECKSUMS.sha256"
TMP="$(mktemp)"

cat >"$TMP" <<EOF
# Xantham blueprint SHA256 manifest
# Regenerated by scripts/update-checksums.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Hasher: $SHA_CMD
#
# Verify locally on macOS:    shasum -a 256 xantham-system-v31.md xantham-templates-v31.md LICENSE README.md
# Verify locally on Linux:    sha256sum xantham-system-v31.md xantham-templates-v31.md LICENSE README.md
# Or one-shot via the verifier:
#   bash scripts/verify-blueprint.sh           # against main
#   bash scripts/verify-blueprint.sh <sha>     # against a pinned commit
#
EOF

# Both sha256sum and `shasum -a 256` emit the same canonical format:
#   <hex64>  <filename>
( $SHA_CMD "${FILES[@]}" ) >>"$TMP"

mv "$TMP" "$OUT"
echo "Wrote $OUT:"
cat "$OUT"

if command -v git >/dev/null 2>&1; then
  if git diff --quiet -- "$OUT" 2>/dev/null; then
    echo
    echo "No change to $OUT."
  else
    echo
    echo "$OUT updated. Stage it with: git add $OUT"
  fi
fi
